// <auto-generated />
using System;
using CroHoliCityAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CroHoliCityAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230625122858_topostgre")]
    partial class topostgre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CroHoliCityAPI.Model.Dan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NazivDan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NeradniDan")
                        .HasColumnType("boolean");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VrijediDo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VrijediOd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Kalendar");
                });

            modelBuilder.Entity("CroHoliCityAPI.Model.Lokacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naselje")
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostanskiBroj")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VrijediDo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VrijediOd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Zupanija")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lokacije");
                });
#pragma warning restore 612, 618
        }
    }
}
